spring:
  application:
    name: library-management-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:librarydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: ${FLYWAY_ENABLED:false}
    baseline-on-migrate: true
    locations: classpath:db/migration
